version: "3.0"
   
services:
  db:
    container_name: db_dev
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movieguessr
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  web:
    container_name: web_dev
    build: 
      context: ./app
      target: dev
    volumes:
      - ./app:/home/app/web
    command: sh -c "
      /wait &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py makemigrations movieguessr &&
      python3 manage.py migrate --fake-initial &&
      python3 manage.py loaddata initial_movies.json &&
      gunicorn movieguessr.wsgi:application --bind 0.0.0.0:8000 --reload"
    expose:
      -  8000
    env_file: .env.dev
    depends_on:
      - db
    
  nginx:
    container_name: nginx_dev
    build: ./nginx
    volumes:
      - ./app:/home/app/web
    ports:
      - 8000:80
    depends_on:
      - web
