version: "3.9"
   
services:
  db:
    container_name: db_prod
    image: postgres
    volumes:
      - ./app/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    container_name: web_prod
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: sh -c "
      /wait &&
      python3 manage.py migrate &&
      gunicorn movieguessr.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - WAIT_HOSTS=db:5432
    depends_on:
      - db
    