version: "3.9"
   
services:
  db:
    container_name: db_prod
    image: postgres
    # volumes:
    #   - ./app/data/db:/var/lib/postgresql/data
    env_file: .env.prod

  web:
    container_name: web_prod
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: sh -c "
      /wait &&
      python3 manage.py migrate &&
      gunicorn movieguessr.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file: .env.prod
    depends_on:
      - db
    
  nginx:
    build: ./nginx
    # volumes:
    #   - static_volume:/home/app/web/staticfiles
    #   - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web