version: "3.0"
   
services:
  db:
    image: mysql
    restart: always
    env_file: .env.prod
    logging:
      driver: awslogs
      options:
        awslogs-group: MovieGuessrLogs
        awslogs-stream-prefix: db
        awslogs-region: eu-west-2

  web:
    image: idylank/movieguessr:web
    restart: always
    volumes:
      - ./app/static:/home/app/web/static
      - ./app/media:/home/app/web/media
    command: sh -c "
      /wait &&
      gunicorn movieguessr.wsgi:application --bind 0.0.0.0:8000"
    env_file: .env.prod
    links:
      - db
    logging:
      driver: awslogs
      options:
        awslogs-group: MovieGuessrLogs
        awslogs-stream-prefix: web
        awslogs-region: eu-west-2
    
  nginx:
    image: idylank/movieguessr:nginx
    restart: always
    volumes:
      - ./app/static:/home/app/web/static
      - ./app/media:/home/app/web/media
    ports:
      - 80:80
    links:
      - web
    logging:
      driver: awslogs
      options:
        awslogs-group: MovieGuessrLogs
        awslogs-stream-prefix: nginx
        awslogs-region: eu-west-2
