version: "3.0"
   
services:
  web:
    image: idylank/movieguessr:web
    restart: always
    command: sh -c "
      python3 manage.py migrate &&
      python3 manage.py collectstatic --noinput &&
      gunicorn movieguessr.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=False
      - S3=True
      - ALLOWED_HOSTS=* # TODO: NOT SECURE * allowing all hosts
    logging:
      driver: awslogs
      options:
        awslogs-group: MovieGuessrLogs
        awslogs-stream-prefix: web
        awslogs-region: eu-west-2
    
  nginx:
    image: idylank/movieguessr:nginx
    restart: always
    ports:
      - 80:80
    links:
      - web
    logging:
      driver: awslogs
      options:
        awslogs-group: MovieGuessrLogs
        awslogs-stream-prefix: nginx
        awslogs-region: eu-west-2
