version: "3.9"
   
services:
  db:
    container_name: db_prod
    image: postgres
    env_file: .env.prod

  web:
    container_name: web_prod
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - ./app/static:/home/app/web/static
      - ./app/media:/home/app/web/media
    command: sh -c "
      /wait &&
      gunicorn movieguessr.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file: .env.prod
    depends_on:
      - db
    
  nginx:
    build: ./nginx
    volumes:
      - ./app/static:/home/app/web/static
      - ./app/media:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web