version: "3.0"
   
services:
  db:
    container_name: db_dev
    image: postgres
    env_file: .env.dev

  web:
    container_name: web_dev
    build: 
      context: ./app
      target: base
    volumes:
      - ./app:/home/app/web
    command: sh -c "
      /wait &&
      gunicorn movieguessr.wsgi:application --bind 0.0.0.0:8000 --reload"
    expose:
      -  8000
    env_file: .env.dev
    depends_on:
      - db
    
  nginx:
    container_name: nginx_dev
    build: ./nginx
    volumes:
      - ./app:/home/app/web
    ports:
      - 8000:80
    depends_on:
      - web
