version: "3.9"
   
services:
  db:
    container_name: db_dev
    image: postgres
    env_file: .env.dev

  web:
    container_name: web_dev
    build: ./app
    command: sh -c "
      /wait &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/movieguessr
    ports:
      - "8000:8000"
    env_file: .env.dev
    depends_on:
      - db
    