version: "3.0"
   
services:
  web:
    image: idylank/movieguessr:web
    restart: always
    volumes:
      - ./app/static:/home/app/web/static
      - ./app/media:/home/app/web/media
    command: sh -c "
      gunicorn movieguessr.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=* # TODO: NOT SECURE * allowing all hosts
    logging:
      driver: awslogs
      options:
        awslogs-group: MovieGuessrLogs
        awslogs-stream-prefix: web
        awslogs-region: eu-west-2
    
  nginx:
    image: idylank/movieguessr:nginx
    restart: always
    volumes:
      - ./app/static:/home/app/web/static
      - ./app/media:/home/app/web/media
    ports:
      - 80:80
    links:
      - web
    logging:
      driver: awslogs
      options:
        awslogs-group: MovieGuessrLogs
        awslogs-stream-prefix: nginx
        awslogs-region: eu-west-2
