# Generated by Django 4.0.3 on 2022-03-24 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image_url', models.URLField(null=True)),
                ('genres', models.CharField(max_length=100, null=True)),
                ('release_date', models.CharField(max_length=20, null=True)),
                ('actor', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='game date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieguessr.movie')),
            ],
        ),
    ]
