# Generated by Django 4.0.3 on 2022-03-06 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieguessr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='game',
        ),
        migrations.CreateModel(
            name='GameQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieguessr.game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieguessr.question')),
            ],
        ),
    ]
