# Generated by Django 4.0.3 on 2022-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieguessr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='tagline',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
