# Generated by Django 4.0.3 on 2022-03-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieguessr', '0002_user_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='total_score',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
