# Generated by Django 4.0.3 on 2022-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieguessr', '0002_movies_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergames',
            name='total_score',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
