# Generated by Django 4.0.3 on 2022-03-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieguessr', '0004_alter_usergame_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
