name: Build Test and push
on: [push]
env:
  IMAGE_NAME: movieguessr
  REPO_NAME: idylank

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run docker
        run: |
          make dev
      # - name: run docker
      #   run: |
      #     docker run -d -e 8080:8080 -host=172.17.0.2 $REPO_NAME/$IMAGE_NAME:latest && \
      #       docker ps && sleep 5

      - name: Run Django API  Tests
        id: run-api-tests
        run: docker exec web_dev python3 manage.py test movieguessr/tests/
      - name: Output summary to console
        run: echo ${{ steps.run-api-tests.outputs.summary }}

    # - name: Login to Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}

    # - name: Push image to docker hub Container Registry
    #   run: |
    #     docker push $REPO_NAME/$IMAGE_NAME
