name: Build Test and push
on: [push]
env:
  IMAGE_NAME: movieguessr
  REPO_NAME: idylank
  WAIT_HOSTS: localhost:8000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Build and run docker
        run: make test
      - name: Wait for Container to host webpage
        run: wget https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait && chmod +x wait && ./wait
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Django API  Tests
        id: run-api-tests
        run: docker exec web_dev python3 manage.py test movieguessr/tests/
      - name: Output summary to console
        run: echo ${{ steps.run-api-tests.outputs.summary }}

    # - name: Login to Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}

    # - name: Push image to docker hub Container Registry
    #   run: |
    #     docker push $REPO_NAME/$IMAGE_NAME
