name: Build Test and push
on: [push]
env:
  IMAGE_NAME: movieguessr
  REPO_NAME: idylank
  WAIT_HOSTS: localhost:8000

jobs:
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Build and run docker
        run: make test
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: localhost:8000
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
          # Fail this action after this many failed attempts
          max-attempts: 7 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: true # Optional, defaults to "false"
      - name: Run Django API  Tests
        id: run-api-tests
        run: docker exec web_dev python3 manage.py test movieguessr/tests/
      - name: Output summary to console
        run: echo ${{ steps.run-api-tests.outputs.summary }}
  push:
    runs-on: ubuntu-latest
    needs: django-tests  
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push image to docker hub Container Registry
        run: make prod
  deploy: 
    runs-on: ubuntu-latest
    needs: push
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Install ECS CLI
        run: 
          mkdir -p "$HOME/tools/ecs-cli" &&
          curl -Lo "$HOME/tools/ecs-cli/ecs-cli" https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest &&
          chmod +x "$HOME/tools/ecs-cli/ecs-cli" &&
          echo "$HOME/tools/ecs-cli" >> $GITHUB_PATH
      # The .env.prod is a dummy, to make sure the ecs-cli compose will work. The actual keys are set in the 
      # AWS Security Key manger. 
      - name: Deploy to AWS
        run:
          cp .env.dev .env.prod && 
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" &&
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" &&
          export AWS_DEFAULT_REGION=eu-west-2 &&
          ecs-cli compose --file docker-compose.prod.yml --project-name movieguessr service stop --cluster MovieGuessrCluster &&
          ecs-cli compose --file docker-compose.prod.yml --ecs-params ecs-param.yml --project-name movieguessr service up --cluster MovieGuessrCluster
      
